version: '3.8'

services:
  nats:
    image: 'nats:0.8.0'
    ports:
      - "4222:4222"
      - "8222:8222"

  gateway:
    env_file:
      - ./services/gateway/dev.env
    links:
      - nats
      - db
      - redis
    depends_on:
      - nats
      - db
      - redis
    networks:
      - default
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile

  movies:
    env_file:
      - ./services/movies/dev.env
    links:
      - nats
      - db
      - redis
    depends_on:
      - nats
      - db
      - redis
    networks:
      - default
    build:
      context: .
      dockerfile: ./services/movies/Dockerfile

  scraper:
    env_file:
      - ./services/scraper/dev.env
    links:
      - nats
      - db
      - redis
    depends_on:
      - nats
      - db
      - redis
    networks:
      - default
    build:
      context: .
      dockerfile: ./services/scraper/Dockerfile

  db:
    image: postgres:15
    environment:
      POSTGRES_DATABASE: database
      POSTGRES_PASSWORD: password
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  db:
    driver: local